apiVersion: kritis.grafeas.io/v1beta1
kind: VulnzSigningPolicy
metadata:
  name: demo-vsp
spec:
  imageVulnerabilityRequirements:
    maximumFixableSeverity: LOW
    maximumUnfixableSeverity: MEDIUM
    allowlistCVEs:
    # encoding/xml element/attribute namespace prefixes during tokenization
    - projects/goog-vulnz/notes/CVE-2020-29511
    - projects/goog-vulnz/notes/CVE-2020-29509
