#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set -o errexit
set -o pipefail

# needed by the default service account in the cluster to pull images
gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
    --role roles/artifactregistry.reader

setup/cluster "${CLUSTER_NAME}-test"
setup/cluster "${CLUSTER_NAME}-prod"

