#!/bin/bash

# validation 
gcloud=$(which gcloud)   || ( echo "gcloud not found" && exit 1 )

if [[ -z "${PROJECT_ID}" ]]; then
  echo "PROJECT_ID not set, 'export PROJECT_ID=YOUR-PROJECT'."
  exit 1
fi;

ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format="value(account)")
if [[ -z "${ACCOUNT}" ]]; then
  echo "Run 'gcloud auth login' to authenticate on GCP before running this script."
  exit 1
fi;

if [[ -z "${REGION}" ]]; then
  export REGION="us-west1"
fi;

# derived vars 
export PROJECT_NUMBER="$(gcloud projects describe "${PROJECT_ID}" --format='value(projectNumber)')"
export CLOUD_BUILD_SA_EMAIL="${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com"

# cluster variables
export CLUSTER_NAME="demo"
export CLUSTER_NODE_MACHINE_TYPE="e2-medium"
export CLUSTER_RELEASE_CHANNEL="rapid"
export CLUSTER_SIZE="3"
export CLUSTER_ZONE="${REGION}-c"

# pipeline variables
export REGISTRY_NAME="cloudbuild-demo"

# binary authorization variables
export KMS_RING_NAME="binauthz"
export KMS_KEY_NAME="binauthz-signer"
export GCB_ATTESTOR_ID="built-by-cloud-build"
export VULN_ATTESTOR_ID="vulnz-attestor"
export SBOM_ATTESTOR_ID="sbom-attestor"
