#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set -o errexit
set -o pipefail

# configure defaults 
gcloud config set project $PROJECT_ID
gcloud config set artifacts/location $REGION
gcloud config set deploy/region $REGION

echo "Iniatializing project $PROJECT_ID in region $REGION..."

# enables APIs
gcloud services enable \
  artifactregistry.googleapis.com \
  binaryauthorization.googleapis.com \
  cloudbuild.googleapis.com \
  clouddeploy.googleapis.com \
  cloudkms.googleapis.com \
  cloudresourcemanager.googleapis.com \
  container.googleapis.com \
  containerregistry.googleapis.com \
  containerscanning.googleapis.com \
  run.googleapis.com \
  servicenetworking.googleapis.com

# set up IAM roles for Cloud Build service account
gcloud projects add-iam-policy-binding $PROJECT_ID \
  --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
  --role roles/containeranalysis.notes.editor

gcloud projects add-iam-policy-binding $PROJECT_ID \
  --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
  --role roles/containeranalysis.notes.occurrences.viewer

gcloud projects add-iam-policy-binding $PROJECT_ID \
  --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
  --role roles/containeranalysis.occurrences.editor

# TODO: scope this down based on https://github.com/sigstore/cosign/blob/main/KMS.md
gcloud projects add-iam-policy-binding $PROJECT_ID \
  --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
  --role roles/cloudkms.admin

gcloud projects add-iam-policy-binding $PROJECT_ID \
  --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
  --role roles/clouddeploy.operator

gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:$PROJECT_NUMBER-compute@developer.gserviceaccount.com \
    --role roles/clouddeploy.releaser

gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:$PROJECT_NUMBER-compute@developer.gserviceaccount.com \
    --role roles/iam.serviceAccountUser

# add the clouddeploy.jobRunner role to your compute service account
gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:$PROJECT_NUMBER-compute@developer.gserviceaccount.com \
    --role roles/clouddeploy.jobRunner

# add the Kubernetes developer permission:
gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:$PROJECT_NUMBER-compute@developer.gserviceaccount.com \
    --role roles/container.developer

# update templates 
sed -e "s/PROJECT_ID/${PROJECT_ID}/" \
    -e "s/CLUSTER_LOCATION/${CLUSTER_ZONE}/" \
    -e "s/CLUSTER_NAME/${CLUSTER_NAME}/" \
    templates/template.clouddeploy.yaml > app/clouddeploy.yaml

sed -e "s/PROJECT_ID/${PROJECT_ID}/" \
    -e "s/GCB_ATTESTOR/${GCB_ATTESTOR_ID}/" \
    -e "s/VULN_ATTESTOR/${VULN_ATTESTOR_ID}/" \
    templates/template.attestor-policy.yaml > policy/attestor-policy.yaml

# creates the Artifact Registry repo
gcloud artifacts repositories create $REGISTRY_NAME \
  --location $REGION \
  --repository-format=docker

# creates the Google Cloud Deploy pipeline
gcloud deploy apply \
  --project $PROJECT_ID \
  --region $REGION \
  --file app/clouddeploy.yaml

# create key for use in both attestors 
gcloud kms keyrings create $KMS_RING_NAME \
  --project $PROJECT_ID \
  --location $REGION

gcloud kms keys create $KMS_KEY_NAME \
  --project $PROJECT_ID \
  --location $REGION \
  --keyring $KMS_RING_NAME \
  --purpose "asymmetric-signing" \
  --default-algorithm "rsa-sign-pkcs1-4096-sha512"

# grants the GCB service account access to the key
gcloud kms keys add-iam-policy-binding $KMS_KEY_NAME \
    --keyring $KMS_RING_NAME \
    --location $REGION \
    --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
    --role roles/cloudkms.signerVerifier

gcloud kms keys add-iam-policy-binding $KMS_KEY_NAME \
    --keyring $KMS_RING_NAME \
    --location $REGION \
    --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
    --role roles/cloudkms.viewer
