#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set -o errexit
set -o pipefail

# configure defaults 
gcloud config set project $PROJECT_ID
gcloud config set artifacts/location $REGION
gcloud config set deploy/region $REGION
gcloud config set compute/region $REGION
gcloud config set compute/zone $CLUSTER_ZONE

echo "Iniatializing project $PROJECT_ID in region $REGION..."

# enables APIs
gcloud services enable \
  artifactregistry.googleapis.com \
  binaryauthorization.googleapis.com \
  cloudbuild.googleapis.com \
  clouddeploy.googleapis.com \
  cloudkms.googleapis.com \
  cloudresourcemanager.googleapis.com \
  compute.googleapis.com \
  container.googleapis.com \
  containerregistry.googleapis.com \
  containerscanning.googleapis.com \
  containersecurity.googleapis.com \
  run.googleapis.com \
  servicenetworking.googleapis.com 


# set up IAM roles for Cloud Build service account
declare -a cloudbuild_roles=(
  "roles/containeranalysis.notes.editor"
  "roles/containeranalysis.notes.occurrences.viewer"
  "roles/containeranalysis.occurrences.editor"
  "roles/binaryauthorization.attestorsViewer"
  "roles/cloudkms.cryptoKeyDecrypter"
  "roles/cloudkms.signerVerifier"
  "roles/containeranalysis.notes.attacher"
  "roles/clouddeploy.operator"
  "roles/cloudkms.admin" # TODO: scope this down
)

for r in "${cloudbuild_roles[@]}"
do
  gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
    --role $r
done

# deploy
declare -a clouddeploy_roles=(
  "roles/clouddeploy.releaser"
  "roles/iam.serviceAccountUser"
  "roles/clouddeploy.jobRunner"
  "roles/container.developer"
)

for r in "${clouddeploy_roles[@]}"
do
  gcloud projects add-iam-policy-binding $PROJECT_ID \
    --member serviceAccount:$PROJECT_NUMBER-compute@developer.gserviceaccount.com \
    --role $r
done

# update templates 
sed -e "s/PROJECT_ID/${PROJECT_ID}/" \
    -e "s/CLUSTER_LOCATION/${CLUSTER_ZONE}/" \
    -e "s/CLUSTER_NAME/${CLUSTER_NAME}/" \
    templates/template.clouddeploy.yaml > app/clouddeploy.yaml

sed -e "s/PROJECT_ID/${PROJECT_ID}/" \
    -e "s/GCB_ATTESTOR/${GCB_ATTESTOR_ID}/" \
    -e "s/VULN_ATTESTOR/${VULN_ATTESTOR_ID}/" \
    -e "s/SBOM_ATTESTOR/${SBOM_ATTESTOR_ID}/" \
    -e "s/CLUSTER_NAME/${CLUSTER_NAME}/" \
    -e "s/CLUSTER_ZONE/${CLUSTER_ZONE}/" \
    templates/template.attestor-policy.yaml > policy/attestor-policy.yaml

# creates the Artifact Registry repo
gcloud artifacts repositories create $REGISTRY_NAME \
  --location $REGION \
  --repository-format=docker

# creates the Google Cloud Deploy pipeline
gcloud deploy apply \
  --project $PROJECT_ID \
  --region $REGION \
  --file app/clouddeploy.yaml

# create key for use in both attestors 
gcloud kms keyrings create $KMS_RING_NAME \
  --project $PROJECT_ID \
  --location $REGION

gcloud kms keys create $KMS_KEY_NAME \
  --project $PROJECT_ID \
  --location $REGION \
  --keyring $KMS_RING_NAME \
  --purpose "asymmetric-signing" \
  --default-algorithm "rsa-sign-pkcs1-4096-sha512"

# grants the GCB service account access to the key
gcloud kms keys add-iam-policy-binding $KMS_KEY_NAME \
    --keyring $KMS_RING_NAME \
    --location $REGION \
    --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
    --role roles/cloudkms.signerVerifier

gcloud kms keys add-iam-policy-binding $KMS_KEY_NAME \
    --keyring $KMS_RING_NAME \
    --location $REGION \
    --member serviceAccount:$PROJECT_NUMBER@cloudbuild.gserviceaccount.com \
    --role roles/cloudkms.viewer
